# Use root/example as user/password credentials
version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    #   command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: product
    volumes:
      #     - ./data/mysql:/var/lib/mysql
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d